name: CD Pipeline

on:
  workflow_run:
    workflows:
      - CI Pipeline
    types:
      - completed
jobs:
  deploy:
    name: Deploy to EC2 on QA branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files from QA branch
        uses: actions/checkout@v2
        with:
          ref: QA
        continue-on-error: false

      - name: Connecting to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.QA_EC2_FE_SSH_PK }}
          REMOTE_HOST: ${{ secrets.QA_EC2_FE_DNS }}
          REMOTE_USER: ${{ secrets.QA_EC2_FE_USERNAME }}
          TARGET: ${{ secrets.QA_EC2_FE_TARGET_DIR }}
        continue-on-error: false
        
          
      - name: Running npm install and build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.QA_EC2_FE_DNS }}
          username: ${{ secrets.QA_EC2_FE_USERNAME }}
          key: ${{ secrets.QA_EC2_FE_SSH_PK }}
          script: |
            echo "Connecting to EC2..."
            cd /home/ubuntu/UEI-Frontend || { echo "Failed to change directory"; exit 1; }
            echo "Current directory after cd: $(pwd)"
            node -v || { echo "Node version check failed"; exit 1; }
            npm -v || { echo "NPM version check failed"; exit 1; }
            npm install || { echo "npm install failed"; exit 1; }
            npm run build || { echo "npm build failed"; exit 1; }
        continue-on-error: false