name: CD Pipeline

on:
  workflow_run:
    workflows:
      - CI Pipeline
    types:
      - completed
jobs:
  deploy:
    name: Deploy to EC2 on QA branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
        with:
          ref: QA

      - name: Connecting to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.QA_EC2_FE_SSH_PK }}
          REMOTE_HOST: ${{ secrets.QA_EC2_FE_DNS }}
          REMOTE_USER: ${{ secrets.QA_EC2_FE_USERNAME }}
          TARGET: ${{ secrets.QA_EC2_FE_TARGET_DIR }}
          
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
           
