name: Push-to-EC2

# Trigger deployment only on push to QA branch Updated
on:
  push:
    branches:
      - QA

jobs:
  deploy:
    name: Deploy to EC2 on QA branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Connecting to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.QA_EC2_FE_SSH_PK }}
          REMOTE_HOST: ${{ secrets.QA_EC2_FE_DNS }}
          REMOTE_USER: ${{ secrets.QA_EC2_FE_USERNAME }}
          TARGET: ${{ secrets.QA_EC2_FE_TARGET_DIR }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.QA_EC2_FE_DNS }}
          username: ${{ secrets.QA_EC2_FE_USERNAME }}
          key: ${{ secrets.QA_EC2_FE_SSH_PK }}
          script: |
            cd home
           
